# Generated by Django 5.1.4 on 2025-01-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_remove_post_caption_post_content_post_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
    ]
